{
 "title": "balenaSense",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ecobee",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bedroom",
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"room\" = 'bedroom')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Bedroom" }
     ]
    },
    {
     "alias": "office1",
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"room\" = 'office1') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Johnoffice" }
     ]
    },
    {
     "alias": "office2",
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"room\" = 'office2') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Office" }
     ]
    },
    {
     "alias": "den",
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"room\" = 'den') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "318386360747" }
     ]
    },
    {
     "alias": "den humidity",
     "measurement": "humidity",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"room\" = 'den') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "den" }
     ]
    },
    {
     "alias": "Outside",
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"room\" = 'den') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "outside" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity", "label": "%" }
   ],
   "targets": [
    {
     "alias": "Ecobee Humidity",
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "balena-sense",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    {
     "measurement": "balena-sense",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "farenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Office",
     "measurement": "balena-sense",
     "query": "SELECT \"temperature\"  / 100 FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "balena_sense_id", "operator": "=", "value": "w1" }
     ]
    },
    {
     "alias": "Office (DHT)",
     "measurement": "balena-sense",
     "query": "SELECT \"temperature\" FROM \"balena-sense\" WHERE (\"balena_sense_id\" = 'dht11') AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "balena_sense_id", "operator": "=", "value": "dht11" }
     ]
    },
    {
     "alias": "Downstairs",
     "measurement": "balena-sense",
     "query": "SELECT \"temperature\" FROM \"balena-sense\" WHERE (\"balena_sense_id\" = 'dht11') AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "balena_sense_id", "operator": "=", "value": "w2" }
     ]
    }
   ]
  },
  {
   "title": "Ecobee",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "bedroom",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Bedroom" }
     ]
    },
    {
     "alias": "office1",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Johnoffice" }
     ]
    },
    {
     "alias": "office2",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Office" }
     ]
    },
    {
     "alias": "den",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "318386360747" }
     ]
    },
    {
     "alias": "outside",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "outside" }
     ]
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Office (DHT)",
     "measurement": "balena-sense",
     "query": "SELECT \"temperature\"*(9.0/5.0)+32 FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "balena_sense_id", "operator": "=", "value": "dht11" }
     ]
    },
    {
     "alias": "Office",
     "measurement": "balena-sense",
     "query": "SELECT \"temperature\"*(9.0/5.0)+32 FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "balena_sense_id", "operator": "=", "value": "w1" }
     ]
    },
    {
     "alias": "Downstairs",
     "measurement": "balena-sense",
     "query": "SELECT \"temperature\"*(9.0/5.0)+32 FROM \"balena-sense\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "*(9/5)+32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "balena_sense_id", "operator": "=", "value": "w2" }
     ]
    }
   ]
  }
 ]
}